### ISSUE TITLE
Django Support

### ISSUE THREAD

**Issue by yannbu** [zenaton/zenaton-python#10]
Implement Django support, similar to Rails, Symfony and Laravel supports.

**Comment by Yungbubu** [comment]
**What is done?**

**Automatic boot of the framework**, allowing to use the framework classes and models. I tried a lot of options, and the most straightforward is putting this into the `client.py` (which could be renamed to something more general in this case). I think it makes sense to put the client init and framework boot code at the same place, because both are steps needed before doing anything in an environment. 

It's just three lines of code:
`django_settings =  os.getenv('ZENATON_DJANGO_SETTINGS')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', django_settings)
django.setup()`

**What can't be done**

**Automatically import tasks and make them available from everywhere  without importing**, simply because this is not how Python works. 

I checked the `autodiscover_tasks()` function of Celery, it is meant to make Celery "aware" of tasks and making it able to run them. But that does not mean the tasks are directly available anywhere in the code.

**What could be done**

**Auto-discover tasks**, pretty much killing the `--boot` parameter. This could be nice but, but I feel this is not only related to the Django subject, in fact it could be done for every library, for any case (framework or not). That would mean scanning all the Zenaton app directory for classes inheriting `Tasks` or `Workflow`. Celery rely on the naming of the folder (i.e: tasks), but what if the tasks and workflow are in several folders? Anyway, this feature is a pretty big development (several hundreds of error-prone code) and I feel it has to be a Zenaton-wide, coordinated development (like Single Task Dispatch, etc). If this feature exists, it has to work really well, and **always** detect **all** the Zenaton classes of the user, and this won't take a few hours to implement.  If we invest time in developing an "auto-importer" completely replacing the `--boot` parameter, why keep it only on the Django side?

Is it worth the time? Is this Zenaton's priority? @geomagilles @Ciboulette 

I will welcome any remarks or question from the team @idabmat, @pylebecq, @TheSquad, @Strato
